version: '3.9'

services:

  db:
    image: postgres:16.1-alpine
    container_name: pg
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: events_core
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.3-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: es
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
  kibana:
    image: kibana:8.8.1
    container_name: kib
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic

  filebeat:
      container_name: filebeat
      image: docker.elastic.co/beats/filebeat:7.8.0
      volumes:
        - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
        - ./logs:/usr/share/filebeat/logs
      environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
      networks:
        - elastic
      links:
        - kibana
        - elasticsearch
      depends_on:
        - elasticsearch
volumes:
  postgresql-data:
    driver: local
    name: pg-data

networks:
  elastic:
    driver: bridge