# Generated by Django 5.0 on 2023-12-29 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('number_of_attendees', models.IntegerField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=450)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('organizer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('event',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='event.event')),
                ('category', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=255)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('image',
                 models.ImageField(blank=True,
                                   null=True,
                                   upload_to='event_pics/')),
                ('payment_type',
                 models.CharField(choices=[('pd', 'Paid'), ('fr', 'Free'),
                                           ('dn', 'Donation')],
                                  max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('event',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to='event.event')),
                ('privacy_type',
                 models.CharField(choices=[('private', 'Private'),
                                           ('public', 'Public')],
                                  max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Event Privacies',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     primary_key=True,
                     serialize=False,
                     to=settings.AUTH_USER_MODEL)),
                ('subscribed_events',
                 models.ManyToManyField(to='event.event')),
            ],
        ),
    ]
