# Generated by Django 5.0 on 2023-12-28 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('profile_picture',
                 models.ImageField(blank=True,
                                   null=True,
                                   upload_to='profile_pics/')),
                ('user',
                 models.OneToOneField(
                     on_delete=django.db.models.deletion.CASCADE,
                     to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('social_media',
                 models.CharField(choices=[('DI', 'Discord'),
                                           ('FB', 'Facebook'),
                                           ('IG', 'Instagram'),
                                           ('LI', 'LinkedIn'),
                                           ('TW', 'Twitter')],
                                  max_length=2)),
                ('social_profile_name', models.CharField(max_length=150)),
                ('user_profile',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='user_profile.userprofile')),
            ],
        ),
    ]
